openapi: "3.0.1"
info:
  title: Receitas Culinarias
  description: >
    Aplicação de Receitas Culinárias.
    Um website de receitas culinárias é uma aplicação em que usuários divulgam suas receitas para outros usuários da rede.
    Esses receitas possuem título, descrição, ingredientes, modo de preparo, tempo de preparo e uma imagem correspondente.
    As receitas também podem ser avaliadas pelos usuários, com estrelas de 1 a 5, o que aparece é a média das avaliações.
    As receitas podem ser comentadas por outros usuários, para construir uma feedback da receita ao dono da receita.
    Nessa versão, há cadastro de todas as entidades com suporte geral, mas não há segurança de dados.
  version: "1.0"
servers:
  - url: http://{host}:{porta}/api
    variables:
      host:
        default: localhost
      porta:
        default: "8000"

paths:
  /usuario:
    get:
      operationId: UsuarioIndex
      summary: Retornar todos os usuários
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/usuario"
    post:
      operationId: UsuarioStore
      summary: Criar um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                matricula:
                  type: string
                  nullable: true #o que foi adicionado foi isso, para aceitar o campo null
                email:
                  type: string
                senha:
                  type: string
      responses:
        "201":
          description: Usuário Criado

  /usuario/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer

    get:
      operationId: UsuarioShow
      summary: Acessar informações de usuário
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/usuario"
        404:
          description: Usuário não encontrado.

    put:
      operationId: UsuarioUpdate
      summary: Alterar informações de usuário
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  nullable: true
                email:
                  type: string
                  nullable: true
                matricula:
                  type: string
                  nullable: true
      responses:
        200:
          description: OK
        401:
          description: Houve um erro ao alterar as informações.
        404:
          description: Usuário não encontrado.

    delete:
      operationId: UsuarioDestroy
      summary: Apagar usuário
      responses:
        200:
          description: OK
        404:
          description: Usuário não encontrado.

  /receita:
    get:
      operationId: ReceitaIndex
      summary: Retornar todas as Receitas
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/receita"
    post:
      operationId: ReceitaStore
      summary: Criar uma nova receita
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario_id:
                  type: integer
                titulo:
                  type: string
                ingredientes:
                  type: string
                modo_de_preparo:
                  type: string
                tempo_de_preparo:
                  type: string
                image:
                  type: string
      responses:
        "201":
          description: Receita Criada

  /avaliacao:
    get:
      operationId: AvaliacaoIndex
      summary: Retorna todas as avaliações
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/avaliacao"
    post:
      operationId: AvaliacaoStore
      summary: Criar uma nova avaliação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario_id:
                  type: integer
                receita_id:
                  type: integer
                estrelas:
                  type: integer
      responses:
        "201":
          description: Avaliação Criada

components:
  schemas:
    usuario:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: Ana
        matricula:
          type: string
          nullable: true 
          example: 2021001101023
        email:
          type: string
          example: ana.julia@ifrn.edu.br
        senha:
          type: string
          example: senhaForte345@#

    receita:
      type: object
      properties:
        id:
          type: integer
          example: 1
        usuario_id:
          type: integer
          example: 2
        titulo:
          type: string
          example: Frango Assado
        ingredientes:
          type: string
          example: "frango, óleo, cebola, alho"
        modo_de_preparo:
          type: string
          example: "Coloque o óleo na panela, depois corte a cebola e o alho"
        tempo_de_preparo:
          type: string
          example: "40 minutos"
        imagem:
          type: string
          example: frangoassado.png

    avaliacao:
      type: object
      properties:
        receita_id:
          type: integer
          example: 1
        usuario_id:
          type: integer
          example: 2
        estrelas:
          type: integer
          enum: [1, 2, 3, 4, 5]
          example: 5

    comentario:
      type: object
      properties:
        receita_id:
          type: integer
          example: 1
        usuario_id:
          type: integer
          example: 2
        texto:
          type: string
          example: "Muito boa a receita!"